DROP TABLE X7.X7_SLDOPR_H CASCADE CONSTRAINTS;

CREATE TABLE X7.X7_SLDOPR_H
(
  IDTCLT     VARCHAR2(6 CHAR),
  IDTCPTCLT  NUMBER(2),
  IDTTYPOPR  NUMBER(3),
  IDTOPR     NUMBER(10),
  DATDEB     DATE,
  IDTLTT     NUMBER,
  DATFIN     DATE,
  MNT        NUMBER,
  SLD        NUMBER,
  DATTRT     DATE,
  DATCRT     DATE,
  DATEXG     DATE,
  RFR        VARCHAR2(30 CHAR)
)
TABLESPACE DATA2_X7
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;


CREATE INDEX X7.IDX_X7SLDOPR_H ON X7.X7_SLDOPR_H
(DATTRT)
LOGGING
TABLESPACE INDEX_X7
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX X7.X7_SLDOPR_H_IDX1 ON X7.X7_SLDOPR_H
(DATTRT, IDTOPR)
LOGGING
TABLESPACE INDEX_X7
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE PUBLIC SYNONYM X7_SLDOPR_H FOR X7.X7_SLDOPR_H;


GRANT SELECT ON X7.X7_SLDOPR_H TO APPLICATIF_DSI;

GRANT SELECT ON X7.X7_SLDOPR_H TO DPT_SUPPORT;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON X7.X7_SLDOPR_H TO MIGR30;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON X7.X7_SLDOPR_H TO N9APCT;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON X7.X7_SLDOPR_H TO X7SYSADM;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON X7.X7_SLDOPR_H TO X7SYSCAS;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON X7.X7_SLDOPR_H TO X7SYSUSR;
