! --------------------------------------------------------------------------
!   But du module : Définition de constantes 
! --------------------------------------------------------------------------
!                           Constantes 
! --------------------------------------------------------------------------

#ifndef DFT_GNR_H
#define DFT_GNR_H

#define SORTIE_OK           	0
#define SORTIE_ERREUR     	100
#define SORTIE_ERREUR_SQL  	-1

#define VRAI			1
#define FAUX			0

#define TAB			'	'
#define CR			'\n'

#define MSG_FICHIER_HISTORIQUE	'msghst.log'

#define MSG_OK				0
#define MSG_ERR_OUVRIR_FICHIER		1
#define MSG_ERR_ECRITURE_FICHIER	2
#define MSG_ERR_PAS_DE_DATE		4

#endif
