Insert into TCHE ( IDTTYPTCHE, PRM2, STT, IDTAGT, MODDCL, TYPENT, DATDMD) Values ( 'TRT2005', '40836', NULL, 'BATCH', 'B', 'LOT', sysdate);
-- Insert into TCHE ( IDTTYPTCHE, PRM2, STT, IDTAGT, MODDCL, TYPENT, DATDMD) Values ( 'TRT2005', '38821', NULL, 'BATCH', 'B', 'LOT', sysdate);
COMMIT;