DROP VIEW X7.FACTURESXECHEANCIER;

/* Formatted on 01/05/2020 13:22:44 (QP5 v5.185.11230.41888) */
CREATE OR REPLACE FORCE VIEW X7.FACTURESXECHEANCIER
(
   IDTOPRECH,
   RFR_ECH,
   MNTECH,
   IDTOPRFAC,
   RFR_FAC,
   MNTFAC,
   MNTFACECH
)
AS
   SELECT OPR1.IdtOpr IdtOprEch,
          OPR1.EchPmt rfr_ech,
          ABS (opr1.mnt) mntech,
          OPR2.IdtOpr IdtOprFac,
          opr2.rfr rfr_fac,
          opr2.mnt mntfac,
          ltt.mnt mntfacech
     FROM opr opr1, ltt, opr opr2
    WHERE     opr2.idttypopr NOT IN (8, 24)
          AND opr2.idtopr = ltt.idtoprdbt
          AND ltt.mnt > 0
          AND ltt.idtoprcrt = opr1.idtopr
          AND opr1.idttypopr IN (6, 20);


DROP PUBLIC SYNONYM FACTURESXECHEANCIER;

CREATE OR REPLACE PUBLIC SYNONYM FACTURESXECHEANCIER FOR X7.FACTURESXECHEANCIER;


GRANT SELECT ON X7.FACTURESXECHEANCIER TO APPLICATIF_DSI;

GRANT SELECT ON X7.FACTURESXECHEANCIER TO DPT_SUPPORT;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK, MERGE VIEW ON X7.FACTURESXECHEANCIER TO IMPCLT;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK, MERGE VIEW ON X7.FACTURESXECHEANCIER TO MIGR30;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK, MERGE VIEW ON X7.FACTURESXECHEANCIER TO N9APCT;

GRANT DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK, MERGE VIEW ON X7.FACTURESXECHEANCIER TO X7SYSADM;

GRANT DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK, MERGE VIEW ON X7.FACTURESXECHEANCIER TO X7SYSCAS;

GRANT DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK, MERGE VIEW ON X7.FACTURESXECHEANCIER TO X7SYSUSR;
