--------------------------------------
-- regroupement de rubrique
--------------------------------------
drop table X7.RGRRBQ;

CREATE TABLE X7.RGRRBQ
(
  IDTRGRRBQ  VARCHAR2(12)                   NOT NULL,
  LIB        VARCHAR2(254)                 NOT NULL,
  LIBABR     VARCHAR2(127)                 NOT NULL,
  VLRDFT     NUMBER(1)                          NOT NULL,
  LIBINT     VARCHAR2(40)
)
TABLESPACE DATA_X7
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE X7.RGRRBQ IS 'Regroupement de rubrique';
COMMENT ON COLUMN X7.RGRRBQ.IDTRGRRBQ IS 'Regroupement de rubrique ID';
COMMENT ON COLUMN X7.RGRRBQ.LIB IS 'Description';
COMMENT ON COLUMN X7.RGRRBQ.LIBABR IS 'Short wording';
COMMENT ON COLUMN X7.RGRRBQ.VLRDFT IS 'Default value (1 <TRUE>, 0 <FALSE>)';
COMMENT ON COLUMN X7.RGRRBQ.LIBINT IS 'Internal description in english for maintenance purpose';

CREATE UNIQUE INDEX X7.PK_RGRRBQ ON X7.RGRRBQ
(IDTRGRRBQ)
LOGGING
TABLESPACE INDEX_X7
NOPARALLEL;

ALTER TABLE X7.RGRRBQ ADD (
  CONSTRAINT PK_RGRRBQ
  PRIMARY KEY
  (IDTRGRRBQ)
  USING INDEX X7.PK_RGRRBQ
  ENABLE VALIDATE);


GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON X7.RGRRBQ TO X7SYSADM;
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON X7.RGRRBQ TO X7SYSCAS;
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON X7.RGRRBQ TO X7SYSUSR;

CREATE OR REPLACE PUBLIC SYNONYM RGRRBQ FOR X7.RGRRBQ;



ALTER TABLE X7.RBQ  ADD (IDTRGRRBQ  VARCHAR2(12));

ALTER TABLE X7.RBQ ADD (
  CONSTRAINT FK7_RBQ 
  FOREIGN KEY (IDTRGRRBQ) 
  REFERENCES X7.RGRRBQ (IDTRGRRBQ)
  ENABLE VALIDATE);    
  


--------------------------------------
-- Echeancier par rubrique.
--------------------------------------

drop table X7.ECHPMTRBQ;

CREATE TABLE X7.ECHPMTRBQ
(
  IDTOPR     NUMBER(10)                         NOT NULL,
  RFR        VARCHAR2(30)                       NOT NULL,
  IDTFAC     NUMBER(15)                         NOT NULL,
  NUMLGNFCT  NUMBER(6)                          NOT NULL,
  IDTRBQ     VARCHAR2(6)                        NOT NULL,
  ECHPMT     NUMBER(6)                          NOT NULL,
  IDTLTT     NUMBER(15)                         NOT NULL,
  MNTTTC     NUMBER(16,4)                       NOT NULL,
  MNTHT      NUMBER(16,4)                       NOT NULL,
  MNTTVA     NUMBER(16,4)                       NOT NULL,
  SLDTTC     NUMBER(16,4)                       NOT NULL,
  SLDHT      NUMBER(16,4)                       NOT NULL,
  SLDTVA     NUMBER(16,4)                       NOT NULL,
  SLDIMPTTC  NUMBER(16,4)                       NOT NULL,
  SLDIMPHT   NUMBER(16,4)                       NOT NULL,
  SLDIMPTVA  NUMBER(16,4)                       NOT NULL
);

CREATE UNIQUE INDEX X7.PK_ECHPMTRBQ ON X7.ECHPMTRBQ
(IDTFAC, NUMLGNFCT)
LOGGING
TABLESPACE INDEX_X7
NOPARALLEL;


COMMENT ON TABLE X7.ECHPMTRBQ IS 'Imputation des rubriques sur echeancier';

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON X7.ECHPMTRBQ TO X7SYSADM;
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON X7.ECHPMTRBQ TO X7SYSCAS;
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON X7.ECHPMTRBQ TO X7SYSUSR;

CREATE OR REPLACE PUBLIC SYNONYM ECHPMTRBQ FOR X7.ECHPMTRBQ;


